Remove instruction to use plaintext backend for storing GitHub tokens for Unit tests
First of all, it is insecure to store passwords in plain text. It should be discuoraged, not
instructed.

Second, `keyring.backends.file.PlaintextKeyring` is no longer part of the keyring API as to
discourage insecure storage of passwords. If the developer trying to set up the unit tests tries to
follow these instructions verbatum they will fail with the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'keyring.backends' has no attribute 'file'
```